licenses(["notice"])

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "face_effect_gpu",
    deps = [
        "//mediapipe/examples/desktop:facial_effect",
        "//mediapipe/graphs/face_effect:face_effect_gpu_deps",
    ],
)